# Generated by Django 5.2.1 on 2025-07-30 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('base_currency', models.CharField(help_text='Currency code, e.g., USD', max_length=10, verbose_name='Base Currency')),
                ('target_currency', models.CharField(help_text='Currency code, e.g., BDT', max_length=10, verbose_name='Target Currency')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Exchange rate from base to target currency', max_digits=10, verbose_name='Exchange Rate')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the exchange rate was fetched', verbose_name='Fetched At')),
            ],
            options={
                'verbose_name': 'Exchange Rate Log',
                'verbose_name_plural': 'Exchange Rate Logs',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the plan in USD', max_digits=10, verbose_name='Price')),
                ('duration_days', models.PositiveIntegerField(help_text='Duration of the plan in days', verbose_name='Duration (Days)')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20, verbose_name='Status')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_subscriptions', to='services.plan', verbose_name='Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-id'],
            },
        ),
    ]
